name: PR (additional rules)

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
  merge_group:
  push:
    branches:
      - 'renovate/**'

jobs:
  no-meeting-discuss-label:
    name: No "Meeting Discuss" label
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@4e9ef4ce8c697cf55716ecbf7f13a3d9e0b6ac6a # v5
        if: github.event_name == 'pull_request'
        with:
          mode: exactly
          count: 0
          labels: "Meeting Discuss"
